version: '3.8'
name: 'desafio-shopper'
services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
    - SYS_NICE

  server:
    container_name: shopper-server
    build: ./server
    working_dir: /server
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:${PORT}"]
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: shopper-client
    build: ./web
    working_dir: /web
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:${WEB_PORT}"] 
      timeout: 10s
      retries: 5
    depends_on:
        server:
          condition: service_healthy
